#!/usr/bin/env python3
"""Collect local Stage 1 KeOps code-generation evidence and smoke results.

This is a KeOps-specific helper, not the Stage 1 top-level runner. The
top-level local runner lives in the Basic repo and invokes this helper when
KeOps generated-kernel evidence is needed.
"""

from __future__ import annotations

import shutil
import sys
from datetime import datetime
from pathlib import Path

from keops_stage1_common import (
    EXPECTED_TIMING_SCOPE,
    PRECISIONS,
    SvmWorkload,
    collect_generated_kernel_rows,
    correctness_stats,
    ground_truth_path,
    keops_command,
    matrix_shape,
    parse_metrics,
    require_files,
    run_command,
    run_env,
    run_shell_capture,
    write_csv,
    write_inventory,
    write_text,
)


MACHINE = "local-3080ti"
KEOPS_ROOT = Path("/home/ubuntu/Documents/workspace/GPU-accelerated_Kernel_Density_Exact/baselines/keops-stage1")
HELPER = KEOPS_ROOT / "scripts/keops_exact_kde.py"
PYTHON_BIN = sys.executable
CUDA_HOME = Path("/usr/local/cuda-12.6")

DATA_ROOT = Path("/home/ubuntu/Documents/workspace/dataset/GPU-accelerated_Kernel_Density_Computation")
TMP_ROOT = Path("/home/ubuntu/Documents/workspace/GPU-accelerated_Kernel_Density_Exact/tmp-results/stage1/local-smoke/keops")
GROUND_TRUTH_ROOT = Path("/home/ubuntu/Documents/workspace/dataset/GPU-accelerated_Kernel_Density_Computation/exact/experiments/stage0/ground_truth")

SMOKE_QUERY_ROWS = 100
SMOKE_BATCH_SIZE = 100
TIMEOUT_SECONDS = 600

WORKLOADS = (
    SvmWorkload(
        "svm_susy",
        "SUSY",
        DATA_ROOT / "susy/SUSY_X.data",
        DATA_ROOT / "susy/SUSY_qSet.data",
    ),
    SvmWorkload(
        "svm_home",
        "Home",
        DATA_ROOT / "home/HT_Sensor_dataset_X.data",
        DATA_ROOT / "home/HT_Sensor_dataset_qSet.data",
    ),
    SvmWorkload(
        "svm_miniboone",
        "MiniBooNE",
        DATA_ROOT / "miniboone/MiniBooNE_X.data",
        DATA_ROOT / "miniboone/MiniBooNE_qSet.data",
    ),
)


def write_query_subset(src: Path, dst: Path, rows: int) -> None:
    src_rows, dim = matrix_shape(src)
    keep_rows = min(rows, src_rows)
    dst.parent.mkdir(parents=True, exist_ok=True)
    with src.open("r", encoding="utf-8") as source, dst.open("w", encoding="utf-8") as target:
        source.readline()
        target.write(f"{keep_rows} {dim}\n")
        copied = 0
        while copied < keep_rows:
            line = source.readline()
            if not line:
                break
            if line.strip():
                target.write(line)
                copied += 1
    if copied != keep_rows:
        raise RuntimeError(f"Could not copy {keep_rows} rows from {src}")


def write_vector_subset(src: Path, dst: Path, rows: int) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    copied = 0
    with src.open("r", encoding="utf-8") as source, dst.open("w", encoding="utf-8") as target:
        while copied < rows:
            line = source.readline()
            if not line:
                break
            if line.strip():
                target.write(line)
                copied += 1
    if copied != rows:
        raise RuntimeError(f"Could not copy {rows} values from {src}")


def main() -> int:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = TMP_ROOT / f"{MACHINE}_{timestamp}"
    commands_file = run_dir / "commands.sh"
    inventory_file = run_dir / "machine_inventory.txt"
    generated_file = run_dir / "keops_generated_kernels.csv"
    smoke_file = run_dir / "local_smoke.csv"
    cache_root = run_dir / "keops-cache"

    run_dir.mkdir(parents=True, exist_ok=True)
    write_text(
        commands_file,
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n\n"
        f"# Generated by {Path(__file__).name} at {timestamp}.\n\n",
    )
    commands_file.chmod(0o755)

    require_files([HELPER, *[w.data_path for w in WORKLOADS], *[w.query_path for w in WORKLOADS]])

    env = run_env(KEOPS_ROOT, CUDA_HOME)
    git_branch = run_shell_capture(["git", "rev-parse", "--abbrev-ref", "HEAD"], KEOPS_ROOT, env)
    git_commit = run_shell_capture(["git", "rev-parse", "HEAD"], KEOPS_ROOT, env)
    write_inventory(
        inventory_file,
        machine=MACHINE,
        timestamp=timestamp,
        keops_root=KEOPS_ROOT,
        helper=HELPER,
        data_root=DATA_ROOT,
        tmp_root=TMP_ROOT,
        ground_truth_root=GROUND_TRUTH_ROOT,
        cuda_home=CUDA_HOME,
        python_bin=PYTHON_BIN,
        git_branch=git_branch,
        git_commit=git_commit,
        env=env,
    )

    generated_rows: list[dict[str, str]] = []
    smoke_rows: list[dict[str, str]] = []
    for workload in WORKLOADS:
        subset_query = run_dir / "query-subsets" / f"{workload.workload}_{SMOKE_QUERY_ROWS}.data"
        write_query_subset(workload.query_path, subset_query, SMOKE_QUERY_ROWS)
        smoke_workload = SvmWorkload(
            workload.workload,
            workload.dataset,
            workload.data_path,
            subset_query,
            workload.scale_value,
        )
        reference = run_dir / "reference-subsets" / f"{workload.workload}_{SMOKE_QUERY_ROWS}.out"
        write_vector_subset(ground_truth_path(GROUND_TRUTH_ROOT, workload), reference, SMOKE_QUERY_ROWS)

        for precision in PRECISIONS:
            precision_cache = cache_root / workload.workload / precision.precision.lower()
            precision_env = run_env(KEOPS_ROOT, CUDA_HOME, precision_cache)
            output_path = (
                run_dir
                / "outputs"
                / workload.workload
                / precision.precision.lower()
                / f"{workload.workload}_{precision.precision.lower()}_smoke.out"
            )
            log_path = (
                run_dir
                / "logs"
                / workload.workload
                / f"{workload.workload}_{precision.precision.lower()}_smoke.log"
            )
            command = keops_command(
                PYTHON_BIN,
                HELPER,
                KEOPS_ROOT,
                smoke_workload,
                precision,
                SMOKE_BATCH_SIZE,
                output_path,
            )
            output_path.parent.mkdir(parents=True, exist_ok=True)
            print(f"[RUN] local smoke {workload.workload} {precision.precision}", flush=True)
            return_code, wall_seconds, log_text, timed_out = run_command(
                command,
                log_path,
                commands_file,
                KEOPS_ROOT,
                precision_env,
                TIMEOUT_SECONDS,
            )
            metrics = parse_metrics(log_text)
            status = "timeout" if timed_out else ("ok" if return_code == "0" else f"failed({return_code})")
            if status == "ok" and metrics.get("timing_scope") != EXPECTED_TIMING_SCOPE:
                status = "missing_or_bad_timing"
            if status == "ok" and metrics.get("query_count") != str(SMOKE_QUERY_ROWS):
                status = "bad_query_count"

            stats = correctness_stats(output_path, reference)
            generated_rows.extend(
                collect_generated_kernel_rows(MACHINE, workload, precision, precision_cache, run_dir)
            )
            smoke_rows.append({
                "machine": MACHINE,
                "workload": workload.workload,
                "precision": precision.precision,
                "dtype": precision.dtype,
                "query_rows": str(SMOKE_QUERY_ROWS),
                "batch_size": str(SMOKE_BATCH_SIZE),
                "runtime_s": metrics.get("execution_seconds", ""),
                "qps": metrics.get("qps", ""),
                "max_abs_err": stats["max_abs_err"],
                "max_rel_err": stats["max_rel_err"],
                "return_code": return_code,
                "timeout_seconds": str(TIMEOUT_SECONDS),
                "cli_wall_seconds": f"{wall_seconds:.9f}",
                "output_path": str(output_path),
                "log_path": str(log_path),
                "status": status if stats["status"] == "ok" else stats["status"],
                "git_branch": git_branch,
                "git_commit": git_commit,
            })

    generated_fields = [
        "machine",
        "workload",
        "precision",
        "dtype",
        "dim",
        "cache_root",
        "source_path",
        "nfo_path",
        "copied_source_path",
        "copied_nfo_path",
        "source_sha256",
        "nfo_sha256",
        "status",
    ]
    smoke_fields = [
        "machine",
        "workload",
        "precision",
        "dtype",
        "query_rows",
        "batch_size",
        "runtime_s",
        "qps",
        "max_abs_err",
        "max_rel_err",
        "return_code",
        "timeout_seconds",
        "cli_wall_seconds",
        "output_path",
        "log_path",
        "status",
        "git_branch",
        "git_commit",
    ]
    write_csv(generated_file, generated_rows, generated_fields)
    write_csv(smoke_file, smoke_rows, smoke_fields)

    # Keep copied source evidence and logs, but remove the temporary KeOps cache.
    if cache_root.exists():
        shutil.rmtree(cache_root)

    print(f"[DONE] run_dir={run_dir}")
    print(f"[DONE] generated={generated_file}")
    print(f"[DONE] smoke={smoke_file}")
    failures = [row for row in smoke_rows if row["status"] != "ok"]
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
